services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_PROFILE: ${INSTALL_PROFILE-core}
        PRELOAD_LOCAL_MODELS: ${PRELOAD_LOCAL_MODELS-false}
        ENABLE_PYODIDE: ${ENABLE_PYODIDE-false}
        VITE_SOURCEMAP: ${VITE_SOURCEMAP-false}
        WEBUI_VERSION: ${WEBUI_VERSION-0.2.5}
        WEBUI_BUILD_HASH: ${WEBUI_BUILD_HASH-unknown}
        HALO_RUNTIME_PROFILE: ${HALO_RUNTIME_PROFILE-main}
    image: ghcr.io/sanjinze47/halowebui:${WEBUI_DOCKER_TAG-latest}
    pull_policy: always
    container_name: halowebui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY-}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
